# Site settings
title: Jack Poulson
email: poulson@stanford.edu
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/~poulson" # the subpath of your site, e.g. /blog/
url: "http://web.stanford.edu" # the base hostname & protocol for your site
github_username:  poulson

# Build settings
markdown: kramdown
